import random
import turtle as t


wronggg=''

# Set up turtle screen
wn = t.Screen()
wn.setup(width=600, height=600)
def setup():
    t.penup()
    t.goto(-100, -100)
    t.pendown()
    
    t.forward(100)
    t.left(180)
    t.forward(50)
    t.right(90)
    t.forward(110)
    t.right(90)
    t.forward(80)
    t.right(90)
    t.forward(20)

def head():
    t.pendown()
    t.circle(15)

def body():
    t.forward(70)

def leftarm():
    t.left(180)
    t.forward(40)
    t.left(90)
    t.forward(30)

def rightarm():
    t.right(180)
    t.forward(60)

def leftleg():
    t.right(180)
    t.forward(30)
    t.left(90)
    t.forward(40)
    t.right(40)
    t.forward(50)

def rightleg():
    t.right(180)
    t.forward(50)
    t.right(50)
    t.forward(60)

# List of words for the game
words = [
    'Canidae',
    'Felidae',
    'Cat',
    'Cattle',
    'Dog',
    'Donkey',
    'Goat',
    'Guinea pig',
    'Horse',
    'Pig',
    'Rabbit',
    'Aardvark',
    'Aardwolf',
    'African buffalo',
    'African elephant',
    'African leopard',
    'Albatross',
    'Alligator',
    'Alpaca',
    'bison',
    'American robin',
    'Amphibian',
    'Anaconda',
    'Angelfish',
    'Anglerfish',
    'Ant',
    'Anteater',
    'Antelope',
    'Ape',
    'Aphid',
    'Arabian leopard',
    'Arctic Fox',
    'Arctic Wolf',
    'Armadillo',
    'Arrow crab',
    'Asp',
    'Ass',
    'Baboon',
    'Badger',
    'Bald eagle',
    'Bandicoot',
    'Barnacle',
    'Barracuda',
    'Basilisk',
    'Bass',
    'Bat',
    'Beaked whale',
    'Bear',
    'Beaver',
    'Bedbug',
    'Bee',
    'Beetle',
    'Bird',
    'Bison',
    'Blackbird',
    'Black panther',
    'Black widow spider',
    'Blue bird',
    'Blue jay',
    'Blue whale',
    'Boa',
    'Boar',
    'Bobcat',
    'Bobolink',
    'Bonobo',
    'Booby',
    'Box jellyfish',
    'Bovid',
    'Buffalo',
    'Bug',
    'Butterfly',
    'Buzzard',
    'Camel',
    'Canid',
    'Cape buffalo',
    'Capybara',
    'Cardinal',
    'Caribou',
    'Carp',
    'Cat',
    'Catshark',
    'Caterpillar',
    'Catfish',
    'Cattle',
    'Centipede',
    'Cephalopod',
    'Chameleon',
    'Cheetah',
    'Chickadee',
    'Chicken',
    'Chimpanzee',
    'Chinchilla',
    'Chipmunk',
    'Clam',
    'Clownfish',
    'Cobra',
    'Cockroach',
    'Cod',
    'Condor',
    'Constrictor',
    'Coral',
    'Cougar',
    'Cow',
    'Coyote',
    'Crab',
    'Crane',
    'Crane fly',
    'Crawdad',
    'Crayfish',
    'Cricket',
    'Crocodile',
    'Crow',
    'Cuckoo',
    'Cicada',
    'Damselfly',
    'Deer',
    'Dingo',
    'Dinosaur',
    'Dog',
    'Dolphin',
    'Donkey',
    'Dormouse',
    'Dove',
    'Dragonfly',
    'Dragon',
    'Duck',
    'Dung beetle',
    'Eagle',
    'Earthworm',
    'Earwig',
    'Echidna',
    'Eel',
    'Egret',
    'Elephant',
    'Elephant seal',
    'Elk',
    'Emu',
    'English pointer',
    'Ermine',
    'Falcon',
    'Ferret',
    'Finch',
    'Firefly',
    'Fish',
    'Flamingo',
    'Flea',
    'Fly',
    'Flyingfish',
    'Fowl',
    'Fox',
    'Frog',
    'Fruit bat',
    'Gamefowl',
    'Galliform',
    'Gazelle',
    'Gecko',
    'Gerbil',
    'Giant panda',
    'Giant squid',
    'Gibbon',
    'Gila monster',
    'Giraffe',
    'Goat',
    'Goldfish',
    'Goose',
    'Gopher',
    'Gorilla',
    'Grasshopper',
    'Great blue heron',
    'Great white shark',
    'Grizzly bear',
    'Ground shark',
    'Ground sloth',
    'Grouse',
    'Guan',
    'Guanaco',
    'Guineafowl',
    'Guinea pig',
    'Gull',
    'Guppy',
    'Haddock',
    'Halibut',
    'Hammerhead shark',
    'Hamster',
    'Hare',
    'Harrier',
    'Hawk',
    'Hedgehog',
    'Hermit crab',
    'Heron',
    'Herring',
    'Hippopotamus',
    'Hookworm',
    'Hornet',
    'Horse',
    'Hoverfly',
    'Hummingbird',
    'Humpback whale',
    'Hyena',
    'Iguana',
    'Impala',
    'Irukandji jellyfish',
    'Jackal',
    'Jaguar',
    'Jay',
    'Jellyfish',
    'Junglefowl',
    'Kangaroo',
    'Kangaroo mouse',
    'Kangaroo rat',
    'Kingfisher',
    'Kite',
    'Kiwi',
    'Koala',
    'Koi',
    'Komodo dragon',
    'Krill',
    'Ladybug',
    'Lamprey',
    'Landfowl',
    'Land snail',
    'Lark',
    'Leech',
    'Lemming',
    'Lemur',
    'Leopard',
    'Leopon',
    'Limpet',
    'Lion',
    'Lizard',
    'Llama',
    'Lobster',
    'Locust',
    'Loon',
    'Louse',
    'Lungfish',
    'Lynx',
    'Macaw',
    'Mackerel',
    'Magpie',
    'Mammal',
    'Manatee',
    'Mandrill',
    'Manta ray',
    'Marlin',
    'Marmoset',
    'Marmot',
    'Marsupial',
    'Marten',
    'Mastodon',
    'Meadowlark',
    'Meerkat',
    'Mink',
    'Minnow',
    'Mite',
    'Mockingbird',
    'Mole',
    'Mollusk',
    'Mongoose',
    'Monitor lizard',
    'Monkey',
    'Moose',
    'Mosquito',
    'Moth',
    'Mountain goat',
    'Mouse',
    'Mule',
    'Muskox',
    'Narwhal',
    'Newt',
    'New World quail',
    'Nightingale',
    'Ocelot',
    'Octopus',
    'Old World quail',
    'Opossum',
    'Orangutan',
    'Orca',
    'Ostrich',
    'Otter',
    'Owl',
    'Ox',
    'Panda',
    'Panther',
    'Panthera hybrid',
    'Parakeet',
    'Parrot',
    'Parrotfish',
    'Partridge',
    'Peacock',
    'Peafowl',
    'Pelican',
    'Penguin',
    'Perch',
    'Peregrine falcon',
    'Pheasant',
    'Pig',
    'Pigeon',
    'Pike',
    'Pilot whale',
    'Pinniped',
    'Piranha',
    'Planarian',
    'Platypus',
    'Polar bear',
    'Pony',
    'Porcupine',
    'Porpoise',
    'Portuguese man o war',
    'Possum',
    'Prairie dog',
    'Prawn',
    'Praying mantis',
    'Primate',
    'Ptarmigan',
    'Puffin',
    'Puma',
    'Python',
    'Quail',
    'Quelea',
    'Quokka',
    'Rabbit',
    'Raccoon',
    'Rainbow trout',
    'Rat',
    'Rattlesnake',
    'Raven',
    'Red panda',
    'Reindeer',
    'Reptile',
    'Rhinoceros',
    'Right whale',
    'Roadrunner',
    'Rodent',
    'Rook',
    'Rooster',
    'Roundworm',
    'Saber-toothed cat',
    'Sailfish',
    'Salamander',
    'Salmon',
    'Sawfish',
    'Scale insect',
    'Scallop',
    'Scorpion',
    'Seahorse',
    'Sea lion',
    'Sea slug',
    'Sea snail',
    'Shark',
    'Sheep',
    'Shrew',
    'Shrimp',
    'Silkworm',
    'Silverfish',
    'Skink',
    'Skunk',
    'Sloth',
    'Slug',
    'Smelt',
    'Snail',
    'Snake',
    'Snipe',
    'Snow leopard',
    'Sockeye salmon',
    'Sole',
    'Sparrow',
    'Sperm whale',
    'Spider',
    'Spider monkey',
    'Spoonbill',
    'Squid',
    'Squirrel',
    'Starfish',
    'Star-nosed mole',
    'Steelhead trout',
    'Stingray',
    'Stoat',
    'Stork',
    'Sturgeon',
    'Sugar glider',
    'Swallow',
    'Swan',
    'Swift',
    'Swordfish',
    'Swordtail',
    'Tahr',
    'Takin',
    'Tapir',
    'Tarantula',
    'Tarsier',
    'Tasmanian devil',
    'Termite',
    'Tern',
    'Thrush',
    'Tick',
    'Tiger',
    'Tiger shark',
    'Tiglon',
    'Toad',
    'Tortoise',
    'Toucan',
    'Trapdoor spider',
    'Tree frog',
    'Trout',
    'Tuna',
    'Turkey',
    'Turtle',
    'Tyrannosaurus',
    'Urial',
    'Vampire bat',
    'Vampire squid',
    'Vicuna',
    'Viper',
    'Vole',
    'Vulture',
    'Wallaby',
    'Walrus',
    'Wasp',
    'Warbler',
    'Water Boa',
    'Water buffalo',
    'Weasel',
    'Whale',
    'Whippet',
    'Whitefish',
    'Whooping crane',
    'Wildcat',
    'Wildebeest',
    'Wildfowl',
    'Wolf',
    'Wolverine',
    'Wombat',
    'Woodpecker',
    'Worm',
    'Wren',
    'Xerinae',
    'X-ray fish',
    'Yak',
    'Yellow perch',
    'Zebra',
    'Zebra finch',
    'Alpaca',
    'Bali cattle',
    'Cat',
    'Cattle',
    'Chicken',
    'Dog',
    'Bactrian camel',
    'canary',
    'dromedary camel',
    'duck',
    'goat',
    'goose',
    'guineafowl',
    'hedgehog',
    'pig',
    'pigeon',
    'rabbit',
    'silkmoth',
    'silver fox',
    'turkey',
    'Donkey',
    'Fancy mouse',
    'Fancy rat',
    'Lab rat',
    'Ferret',
    'Gayal',
    'Goldfish',
    'Guinea pig',
    'Guppy',
    'Horse',
    'Koi',
    'Llama',
    'Ringneck dove',
    'Sheep',
    'Siamese fighting fish',
    'Society finch',
    'Yak',
    'Water buffalo'
    ]
setup()

# Choose a random word from the list
word = random.choice(words)
word = word.lower()

# Initialize the guessed word with underscores
guessed_word = ['_'] * len(word)

# Initialize the number of wrong guesses
wrong_guesses = 0

# Loop until the game is over
while True:
    # Print the current state of the guessed word
    print(' '.join(guessed_word))

    # Get a guess from the user
    guess = input('Guess a letter: ').lower()

    # Check if the guess is in the word
    if guess in word:
        # Update the guessed word with the new letter
        for i in range(len(word)):
            if word[i] == guess:
                guessed_word[i] = guess
    else:
        wronggg = wronggg + guess
        print("Sorry, that letter is not in the word.")
        print('Wrong letters:', wronggg)
        # Draw a part of the person
        wrong_guesses += 1
        if wrong_guesses == 1:
            head()
        elif wrong_guesses == 2:
            body()
        elif wrong_guesses == 3:
            leftarm()
        elif wrong_guesses == 4:
            rightarm()
        elif wrong_guesses == 5:
            leftleg()
        elif wrong_guesses == 6:
            rightleg()

    # Check if the game is over
    if wrong_guesses == 6:
        print('Sorry, you lost! The word was', word)
        break
    elif '_' not in guessed_word:
        print('The word was', word)
        print('Congratulations, you won!')
        break
